language: node_js
node_js:
- node

cache:
  yarn: true
  directories:
    - node_modules

script:
- npm run lib

before_deploy:
- cd dist/stripe-payment-component
- export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
- git config --local user.name "$USER_NAME"
- git config --local user.email "$USER_EMAIL"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  api_key: $GH_TOKEN
  overwrite: true
  skip_cleanup: true
  on:
    repo: aAmitSengar/stripe-payment-component
    tags: true
    all_branches: true
