dist: trusty
sudo: false
language: node_js
node_js: node

install:
- npm ci
cache:
  directories:
  - $HOME/.npm
script:
# - npm run test
- npm run lib
deploy:
  deploy:
  provider: npm
  email: "amitsengar@yahoo.com"
  api_key: $NPM_API_KEY
