language: node_js
node_js:
- node

cache:
  yarn: true
  directories:
    - node_modules

script:
- npm run lib

before_deploy:
- cd dist/stripe-payment-component

deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true
